"""add zone field to orders

Revision ID: a8bee170921a
Revises: e2778964d04c
Create Date: 2026-08-02 04:50:10.892487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8bee170921a'
down_revision: Union[str, Sequence[str], None] = 'e2778964d04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('zone', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_orders_zone'), 'orders', ['zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_zone'), table_name='orders')
    op.drop_column('orders', 'zone')
    # ### end Alembic commands ###
