"""Add enterprise legal compliance models

Revision ID: e1778964d04b
Revises: 002
Create Date: 2026-05-26 01:36:31.978372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1778964d04b'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('legal_policy_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('checksum_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_policy_versions_policy_key'), 'legal_policy_versions', ['policy_key'], unique=False)
    op.create_index('ix_policy_key_active', 'legal_policy_versions', ['policy_key', 'active'], unique=False)
    op.create_table('compliance_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_payload', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_audit_logs_actor_id'), 'compliance_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_event_type'), 'compliance_audit_logs', ['event_type'], unique=False)
    op.create_index('ix_compliance_logs_created', 'compliance_audit_logs', ['created_at'], unique=False)
    op.create_table('user_legal_acceptances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('policy_key', sa.String(length=100), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_metadata', sa.JSON(), nullable=True),
    sa.Column('acceptance_source', sa.String(length=100), nullable=True),
    sa.Column('acceptance_method', sa.String(length=100), nullable=True),
    sa.Column('geo_metadata', sa.JSON(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('signature_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_legal_acceptances_user_id'), 'user_legal_acceptances', ['user_id'], unique=False)
    op.create_index('ix_user_policy', 'user_legal_acceptances', ['user_id', 'policy_key'], unique=False)
    op.create_table('driver_decline_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_decline_logs_driver_id'), 'driver_decline_logs', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_decline_logs_order_id'), 'driver_decline_logs', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('driver_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('restaurant_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_order_id'), 'reviews', ['order_id'], unique=False)
    op.create_unique_constraint('uq_order_reviewee', 'reviews', ['order_id', 'reviewee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_reviewee', 'reviews', type_='unique')
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_order_id'), 'reviews', ['order_id'], unique=1)

    op.drop_column('orders', 'restaurant_accepted_at')
    op.drop_column('orders', 'driver_accepted_at')
    op.drop_index(op.f('ix_driver_decline_logs_order_id'), table_name='driver_decline_logs')
    op.drop_index(op.f('ix_driver_decline_logs_driver_id'), table_name='driver_decline_logs')
    op.drop_table('driver_decline_logs')
    op.drop_index('ix_user_policy', table_name='user_legal_acceptances')
    op.drop_index(op.f('ix_user_legal_acceptances_user_id'), table_name='user_legal_acceptances')
    op.drop_table('user_legal_acceptances')
    op.drop_index('ix_compliance_logs_created', table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_event_type'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_actor_id'), table_name='compliance_audit_logs')
    op.drop_table('compliance_audit_logs')
    op.drop_index('ix_policy_key_active', table_name='legal_policy_versions')
    op.drop_index(op.f('ix_legal_policy_versions_policy_key'), table_name='legal_policy_versions')
    op.drop_table('legal_policy_versions')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
